### ISSUE TITLE
2 broken endpoints

### ISSUE THREAD

**Issue by mchingos** [UrbanInstitute/education-data-package-stata#39]
#1: 
. educationdata using "college ipeds completers", clear
Please be patient - Downloading data from API. I'll give you a time estimate shortly.
 Error -675, Unable to open URL: server reported server error
          getalltables():  3010  attempt to dereference NULL pointer
            getalldata():     -  function returned error
                 <istmt>:     -  function returned error

#2:
. educationdata using "college ipeds completers-cip", clear
Error: The name of the category ('school', 'district', or 'college') is correct, but the name of the 
> dataset you chose is not. Please verify the list of allowed options by typing "help educationdata".
.

**Comment by grahamimac** [comment]
On #2, it should be "completions-cip" (or that's what I have in the latest metadata from yesterday, was it updated today?). That works for me.

On #1, that seems to be an error caused by the API endpoint format splitting the years (as a -). @ericatheresa it seems that for endpoint 31, which is college-university ipeds completers, there is no &ndash; for 2011-2015, just a regular dash. Can you fix and reupload when you have a chance? Thanks!

**Comment by ericatheresa** [comment]
Fixed! @ddorio can you re-upload? So sorry!

**Comment by ddorio** [comment]
@ericatheresa @grahamimac  uploaded.....

**Comment by grahamimac** [comment]
Awesome, confirmed fix on the Stata end. Thanks for the find Matt, and the quick fix Erica and Dave!

**Comment by mchingos** [comment]
Still not working, but maybe it takes some time for the fix to go through?
